### PR TITLE
Update Vapor packages

### PR DESCRIPTION
**Pull request by 0xTim**
### Pull Request Description

Updates Vapor's packages to remove archived packages, fix for renames and add new packages

### CODE REVIEW

**Comment by 0xTim** [comment]
@swift-ci test

**Comment by justice-adams-apple** [comment]
@swift-ci test@swift-ci test

**Comment by 0xTim** [comment]
@justice-adams-apple is there anything I need to do for the PR? Looks like the failures are in Penny which hasn't changed in this PR

**Review by justice-adams-apple — APPROVED** [review]
@0xTim Thanks for the PR, sorry for the late reply, I was investigating the CI failure, like you said, not related to this PR, so let's merge it 👍

**Comment by xymus** [comment]
Some of the new packages appear to fail on some bots. It's unclear to me why it wasn't detected by PR testing.

https://github.com/swiftlang/swift/issues/75655
https://github.com/swiftlang/swift/issues/75656

**Pull request merged**
